baseURL = "https://www.martinhubacek.cz/"
languageCode = "en-us"
title = "Martin Hubáček"
theme = "timer-hugo"

[markup.goldmark.renderer]
unsafe= true

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
# [[menu.nav]]
# name    = "About"
# url     = "about"
# weight  = 2
# [[menu.nav]]
# name    = "Service"
# url     = "service"
# weight  = 3
# [[menu.nav]]
# name    = "Gallery"
# url     = "gallery"
# weight  = 4
[[menu.nav]]
name    = "Blog"
url     = "blog"
weight  = 5
[[menu.nav]]
name    = "Contact"
url     = "contact"
weight  = 6

# Site Params
[params]
home = "Home"
logo = "images/pcb_400x400.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "UA-8883016-3"

# Banner Section
[params.banner]
enable  = true
bgImage = "images/bga-challenge.jpg"
heading = "HI, MY NAME IS Martin Hubacek & I AM A"
#description = "WITH 10 YEARS EXPERIENCE, I'VE OCCUPIED MANY ROLES INCLUDING DIGITAL DESIGN DIRECTOR, WEB DESIGNER AND DEVELOPER. THIS SITE SHOWCASES SOME OF MY WORK."
# button
btn     = false
btnText = "Download More"
btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "embedded developer"
[[params.banner.flipText]]
title   = "electronics designer"
[[params.banner.flipText]]
title   = "IoT & LPWAN enthusiast"

# Homepage Blogs Section
[params.blogs]
enable  = true

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT ME"
content = "I design and program embedded electronic devices. I'm familiar with many current microcontrollers, firmware stacks, communication interfaces including low power wireless and IoT."
image   = "images/about/about.jpg"

# Call to Action
[params.cta]
enable  = false
title   = "SO WHAT YOU THINK ?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Contact with me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = false
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-twitter"
url = "https://twitter.com/hubmartin"

[[params.socialIcon]]
icon = "ion-social-youtube"
url = "https://www.youtube.com/user/hubmartin"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "https://www.linkedin.com/in/martin-hub%C3%A1%C4%8Dek-7b8ab335/"
